[phases.setup]
nixPkgs = ['python310', 'gcc', 'libGL', 'glib']

[phases.install]
cmds = [
  'cd backend && python3 -m pip install --upgrade pip && python3 -m pip install "numpy>=1.21.0,<1.27.0" && python3 -m pip install -r requirements.txt'
]

[start]
cmd = 'cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT'
