services:
  # 백엔드 서비스
  - type: web
    name: drone-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      pip install "numpy>=1.21.0,<1.27.0"
      pip install -r requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
