[phases.setup]
nixPkgs = ['python310', 'gcc', 'libGL']

[phases.install]
cmds = [
  'pip install "numpy>=1.21.0,<1.27.0"',
  'pip install -r requirements.txt'
]

[start]
cmd = 'uvicorn app:app --host 0.0.0.0 --port $PORT'